server:
    type: simple
    applicationContextPath: /
    adminContextPath: /admin
    connector:
        type: http
        port: 8083
        reuseAddress: true

logging:
    # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
    level: INFO
    loggers:
        thalia: DEBUG
